blank_issues_enabled: false
contact_links:
  - name: Documentation or Feature Request
    url: https://github.com/ashutosh2011/casa-sync-android/issues
    about: Please report any errors, missing information, or feature requests here.
  - name: I have a question or need support
    url: https://touchlite.in/support
    about: GitHub is for tracking bugs and feature requests. For help and support, please visit our support page.
  - name: Casa Sync Website
    url: https://casasync.in
    about: Visit the Casa Sync website for more information.
